import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { format } from 'date-fns';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import jsPDF from 'jspdf';
import toast from 'react-hot-toast';
import { getErrorMessage } from '../../services/api';
import { PayrollRow, payrollService } from '../../services/payrollService';
import Modal from '../../components/common/Modal';
import { PageLoader } from '../../components/common/LoadingSpinner';
import { useSettings } from '../../contexts/SettingsContext';

const initials = (name = '') => name.split(' ').slice(0, 2).map(word => word[0]).join('').toUpperCase();
const emptyForm = { base_salary: 0, allowances: 0, incentives: 0, deductions: 0, overtime_rate: 0, status: 'draft' };

function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-[18px] border border-[#edf1ef] bg-white shadow-[0_8px_30px_rgba(31,62,53,.035)] ${className}`}>{children}</section>; }

const iconProps = { viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', strokeWidth: 1.8, strokeLinecap: 'round' as const, strokeLinejoin: 'round' as const, className: 'h-6 w-6' };
const SalaryIcon = () => <svg {...iconProps}><path d="M21 12V7H5a2 2 0 0 1 0-4h14v4"/><path d="M3 5v14a2 2 0 0 0 2 2h16v-5"/><path d="M18 12a2 2 0 0 0 0 4h4v-4Z"/></svg>;
const AllowanceIcon = () => <svg {...iconProps}><polyline points="20 12 20 22 4 22 4 12"/><rect x="2" y="7" width="20" height="5"/><line x1="12" y1="22" x2="12" y2="7"/><path d="M12 7H7.5a2.5 2.5 0 0 1 0-5C11 2 12 7 12 7z"/><path d="M12 7h4.5a2.5 2.5 0 0 0 0-5C13 2 12 7 12 7z"/></svg>;
const OvertimeIcon = () => <svg {...iconProps}><circle cx="12" cy="12" r="9"/><polyline points="12 7 12 12 15.5 14"/></svg>;
const IncentiveIcon = () => <svg {...iconProps}><circle cx="12" cy="8" r="6"/><polyline points="8.5 13.2 7 22 12 19 17 22 15.5 13.2"/></svg>;

export default function CeoPayroll() {
  const queryClient = useQueryClient();
  const { money, currency } = useSettings();
  const currencySymbol = useMemo(() => {
    try { return new Intl.NumberFormat(undefined, { style: 'currency', currency }).formatToParts(0).find(p => p.type === 'currency')?.value || currency; }
    catch { return currency; }
  }, [currency]);
  const [month, setMonth] = useState(format(new Date(), 'yyyy-MM'));
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('all');
  const [editing, setEditing] = useState<PayrollRow | null>(null);
  const [form, setForm] = useState(emptyForm);
  const { data, isLoading } = useQuery({ queryKey: ['payroll', month], queryFn: () => payrollService.get(month) });
  const filtered = useMemo(() => (data?.rows || []).filter(row => {
    const term = search.toLowerCase();
    const matchesSearch = !term || [row.user.name, row.user.employee_id, row.user.department, row.user.designation].some(value => value?.toLowerCase().includes(term));
    return matchesSearch && (status === 'all' || row.status === status);
  }), [data?.rows, search, status]);
  const save = useMutation({ mutationFn: () => payrollService.update(editing!.user.id, { month, ...form }), onSuccess: () => { toast.success('Payroll updated'); setEditing(null); queryClient.invalidateQueries({ queryKey: ['payroll', month] }); }, onError: error => toast.error(getErrorMessage(error)) });
  const edit = (row: PayrollRow) => { setEditing(row); setForm({ base_salary: row.base_salary, allowances: row.allowances, incentives: row.incentives, deductions: row.deductions, overtime_rate: row.overtime_rate, status: row.status }); };
  const payslip = (row: PayrollRow) => { const doc = new jsPDF(); doc.setFontSize(20); doc.setTextColor(18,107,91); doc.text('PAYSLIP', 15, 20); doc.setTextColor(30,45,40); doc.setFontSize(11); doc.text(`Employee: ${row.user.name}`, 15, 35); doc.text(`Employee ID: ${row.user.employee_id || '—'}`, 15, 43); doc.text(`Pay period: ${format(new Date(`${month}-01T00:00:00`), 'MMMM yyyy')}`, 15, 51); doc.line(15,58,195,58); [['Base salary',row.base_salary],['Allowances',row.allowances],['Overtime',row.overtime_pay],['Incentives',row.incentives],['Deductions',-row.deductions]].forEach(([label,value],index) => { doc.text(String(label),20,70+index*10); doc.text(money(Number(value)),150,70+index*10); }); doc.line(15,124,195,124); doc.setFontSize(14); doc.text('Net Pay',20,137); doc.text(money(row.total),150,137); doc.setFontSize(9); doc.setTextColor(110); doc.text(`Status: ${row.status.toUpperCase()} • Generated ${format(new Date(),'dd MMM yyyy')}`,15,155); doc.save(`Payslip-${row.user.employee_id || row.user.id}-${month}.pdf`); };
  if (isLoading || !data) return <PageLoader />;
  const monthLabel = format(new Date(`${month}-01T00:00:00`), 'MMM yyyy');
  const stats = [
    ['Total Salary', data.summary.salary, <SalaryIcon/>, 'var(--color-emerald-500, #10b981)'], ['Total Allowances', data.summary.allowances, <AllowanceIcon/>, 'var(--color-emerald-700, #047857)'],
    ['Total Overtime', data.summary.overtime, <OvertimeIcon/>, 'var(--color-emerald-500, #10b981)'], ['Total Incentives', data.summary.incentives, <IncentiveIcon/>, 'var(--color-emerald-700, #047857)'],
  ] as const;
  const breakdown = [
    ['Salary',data.summary.salary,'var(--color-emerald-500, #10b981)'],['Allowances',data.summary.allowances,'var(--color-emerald-700, #047857)'],['Deductions',data.summary.deductions,'#9ca8a3'],['Incentives',data.summary.incentives,'#f4c94f'],['Overtime',data.summary.overtime,'#dfe4e2'],
  ] as const;

  return <div className="min-h-full bg-[#f7f9f8] p-4 text-[#17251f] sm:p-6 lg:p-8"><div className="mx-auto max-w-[1560px]">
    <header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-[26px] font-bold tracking-[-.03em]">Payroll</h1><p className="mt-1 text-sm text-[#8a9691]"><span className="font-semibold text-emerald-600">Dashboard</span> &nbsp;/&nbsp; Payroll</p></div><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><label className="flex h-12 items-center gap-2 rounded-2xl border border-[#edf1ef] bg-white px-4 focus-within:border-emerald-500"><svg className="h-4 w-4 text-emerald-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/></svg><span className="text-xs font-semibold text-[#8a9691]">Month</span><input type="month" value={month} onChange={event => setMonth(event.target.value)} className="bg-transparent text-sm font-semibold text-[#17251f] outline-none"/></label><label className="relative block sm:w-72"><span className="absolute left-4 top-1/2 -translate-y-1/2">⌕</span><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search anything" className="h-12 w-full rounded-2xl border border-[#edf1ef] bg-white pl-11 pr-4 text-sm outline-none focus:border-emerald-500"/></label></div></header>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label,value,icon,color]) => <Card key={label} className="flex items-center justify-between p-5"><div><p className="text-xs text-[#8a9691]">{label}</p><b className="mt-2 block text-3xl tracking-[-.04em]">{money(value)}</b><span className="mt-2 inline-block rounded-md bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700">{monthLabel}</span></div><span className="grid h-14 w-14 place-items-center rounded-xl bg-emerald-50/60 text-3xl" style={{color}}>{icon}</span></Card>)}</div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><Card className="p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold">Payroll Overview</h2></div><div className="mb-2 flex gap-5 text-xs text-[#7f8c87]"><span className="text-emerald-500">● Salary</span><span className="text-emerald-700">● Allowances</span><span className="text-[#e6b82d]">● Incentives</span></div><div className="h-56"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.trend}><defs><linearGradient id="pay" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--color-emerald-500, #10b981)" stopOpacity=".28"/><stop offset="1" stopColor="var(--color-emerald-500, #10b981)" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf1ef"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fontSize:11}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:10}} tickFormatter={value => `${currencySymbol}${Math.round(value/1000)}k`}/><Tooltip formatter={value => money(Number(value))}/><Area type="monotone" dataKey="salary" stroke="var(--color-emerald-500, #10b981)" fill="url(#pay)" strokeWidth={2}/><Area type="monotone" dataKey="allowances" stroke="var(--color-emerald-700, #047857)" fill="transparent" strokeWidth={2}/><Area type="monotone" dataKey="incentives" stroke="#e6b82d" fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></Card>
      <Card className="p-5"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-bold">Payroll Breakdown</h2><input type="month" value={month} onChange={event => setMonth(event.target.value)} className="rounded-xl border-0 bg-emerald-50 px-4 py-2 text-sm font-semibold text-emerald-800 outline-none"/></div><div className="mb-4"><b className="text-3xl">{money(data.summary.total)}</b><span className="ml-2 text-xs text-[#8a9691]">Total Pay This Month</span></div><div className="flex h-12 overflow-hidden rounded-lg">{breakdown.map(([label,value,color]) => <i key={label} title={`${label}: ${money(value)}`} style={{width:`${data.summary.total ? Math.max(1,value/(data.summary.total+data.summary.deductions)*100) : 0}%`,backgroundColor:color}}/>)}</div><div className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-3">{breakdown.map(([label,value,color]) => <div key={label} className="flex gap-2 text-xs"><i className="mt-1 h-3 w-3 shrink-0 rounded-sm" style={{backgroundColor:color}}/><span><b>{label}</b><small className="mt-1 block text-[#8a9691]">{money(value)}</small></span></div>)}</div></Card></div>
    <Card className="mt-5 overflow-hidden"><div className="flex flex-col gap-3 border-b border-[#edf1ef] p-5 sm:flex-row sm:items-center sm:justify-between"><h2 className="text-lg font-bold">Payroll List</h2><div className="flex gap-2"><select value={status} onChange={event => setStatus(event.target.value)} className="rounded-xl border border-[#e5ebe8] px-4 py-2 text-sm outline-none"><option value="all">All statuses</option><option value="draft">Draft</option><option value="unpaid">Unpaid</option><option value="paid">Paid</option></select></div></div><div className="overflow-x-auto"><table className="w-full min-w-[1150px] text-left"><thead className="bg-[#fafbfa] text-[11px] text-[#87938e]"><tr><th className="px-5 py-4">Name</th><th>Job Title</th><th>Salary</th><th>Allowances</th><th>Overtime</th><th>Incentives</th><th>Deductions</th><th>Total</th><th>Status</th><th className="px-5">Payslip</th></tr></thead><tbody className="divide-y divide-[#edf1ef]">{filtered.map((row,index) => <tr key={row.user.id} className="hover:bg-[#fbfdfc]"><td className="px-5 py-4"><button onClick={() => edit(row)} className="flex items-center gap-3 text-left"><span className="grid h-9 w-9 place-items-center rounded-full bg-gradient-to-br from-emerald-500 to-emerald-700 text-[10px] font-bold text-white">{initials(row.user.name)}</span><span><b className="block text-sm">{row.user.name}</b><small className="text-[#8a9691]">{row.user.employee_id || `EMP-${index+1}`}</small></span></button></td><td><b className="block text-sm font-semibold">{row.user.designation || 'Team Member'}</b><small className="text-[#8a9691]">{row.user.department || '—'}</small></td><td>{money(row.base_salary)}</td><td>{money(row.allowances)}</td><td>{money(row.overtime_pay)}<small className="block text-[#8a9691]">{row.overtime_hours}h</small></td><td>{money(row.incentives)}</td><td>{money(row.deductions)}</td><td className="font-bold text-emerald-700">{money(row.total)}</td><td><button onClick={() => edit(row)} className={`rounded-full px-3 py-1 text-xs font-bold capitalize ${row.status==='paid'?'bg-emerald-100 text-emerald-800':row.status==='unpaid'?'bg-amber-50 text-amber-700':'bg-gray-100 text-gray-600'}`}>{row.status}</button></td><td className="px-5"><button onClick={() => payslip(row)} className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700 hover:bg-emerald-100">▣ Download</button></td></tr>)}</tbody></table>{!filtered.length && <p className="p-10 text-center text-sm text-[#8a9691]">No payroll records match this filter.</p>}</div></Card>
  </div>
  <Modal isOpen={Boolean(editing)} onClose={() => setEditing(null)} title={`Payroll — ${editing?.user.name || ''}`}><div className="grid gap-4 sm:grid-cols-2">{([['base_salary','Base Salary'],['allowances','Allowances'],['incentives','Incentives'],['deductions','Deductions'],['overtime_rate','Overtime Rate / Hour']] as const).map(([key,label]) => <label key={key} className="text-sm font-semibold text-[#52615b]">{label}<input type="number" min="0" value={form[key]} onChange={event => setForm({...form,[key]:Number(event.target.value)})} className="mt-1 w-full rounded-xl border border-[#dfe6e3] px-3 py-2.5 outline-none focus:border-emerald-500"/></label>)}<label className="text-sm font-semibold text-[#52615b]">Status<select value={form.status} onChange={event => setForm({...form,status:event.target.value})} className="mt-1 w-full rounded-xl border border-[#dfe6e3] px-3 py-2.5"><option value="draft">Draft</option><option value="unpaid">Unpaid</option><option value="paid">Paid</option></select></label></div><div className="mt-6 flex justify-end gap-2"><button onClick={() => setEditing(null)} className="rounded-xl border px-4 py-2 text-sm">Cancel</button><button onClick={() => save.mutate()} disabled={save.isPending} className="rounded-xl bg-emerald-600 px-5 py-2 text-sm font-semibold text-white hover:bg-emerald-700 disabled:opacity-50">Save Payroll</button></div></Modal>
  </div>;
}
