// ─── Auth & User ─────────────────────────────────────────────────────────────

export type Role = 'employee' | 'tl' | 'manager' | 'ceo';
export type EmploymentType = 'full_time' | 'part_time' | 'contract' | 'intern';
export type UserStatus = 'active' | 'inactive' | 'suspended';
export type CurrentStatus = 'working' | 'on_break' | 'checked_out' | 'absent' | 'on_leave' | 'work_from_home';

export interface Department {
  id: number;
  name: string;
  code: string;
  description?: string;
  is_active: boolean;
  employee_count?: number;
  manager?: UserBrief;
}

export interface Designation {
  id: number;
  title: string;
  description?: string;
  is_active: boolean;
  department?: Department;
  created_by?: number;
}

export interface Shift {
  id: number;
  name: string;
  start_time: string;
  end_time: string;
  grace_minutes: number;
  max_overtime_hours: number;
  is_night_shift: boolean;
  duration_hours: number;
  is_active: boolean;
}

export interface UserBrief {
  id: number;
  employee_id?: string;
  name: string;
  email: string;
  role: Role;
  avatar_url?: string;
  department?: string;
  current_status?: CurrentStatus;
}

export interface User {
  id: number;
  employee_id?: string;
  first_name?: string;
  last_name?: string;
  name: string;           // computed: first_name + last_name (fallback)
  email: string;
  phone?: string;
  gender?: 'male' | 'female' | 'other';
  avatar_url?: string;
  allowed_ip?: string;
  role: Role;
  employment_type: EmploymentType;
  work_mode?: WorkMode;
  status: UserStatus;
  current_status: CurrentStatus;
  department?: Department;
  designation?: Designation;
  shift?: Shift;
  manager?: UserBrief;
  join_date?: string;
  birth_date?: string;
  address?: string;
  emergency_contact?: string;
  education?: Array<{ degree: string; institution: string; year: string; field: string }>;
  annual_leave_balance: number;
  sick_leave_balance: number;
  casual_leave_balance: number;
  created_at?: string;
}

export type ProjectStatus = 'planning' | 'in_progress' | 'on_hold' | 'completed';

export interface Project {
  id: number;
  name: string;
  description?: string;
  status: ProjectStatus;
  start_date?: string;
  due_date?: string;
  project_lead?: UserBrief;
  creator?: UserBrief;
  created_at: string;
}

/** Payload sent to POST /api/users — password is auto-generated by the backend */
export interface CreateEmployeePayload {
  first_name: string;
  last_name: string;
  gender: 'male' | 'female' | 'other';
  birth_date: string;           // YYYY-MM-DD
  email: string;
  phone: string;
  role: 'employee' | 'tl' | 'manager';
  employment_type: EmploymentType;
  work_mode: WorkMode;
  department_id: number;
  designation_id: number;
  shift_id?: number | null;
  manager_id?: number | null;
  join_date?: string;
  address?: string;
  emergency_contact?: string;
  allowed_ip?: string;
  status?: UserStatus;
  new_password?: string;
}

/** Response from POST /api/users */
export interface CreateEmployeeResponse {
  message: string;
  temporary_password: string;
  user: User;
}

// ─── Attendance ───────────────────────────────────────────────────────────────

export type AttendanceStatus = 'present' | 'absent' | 'late' | 'half_day' | 'on_leave' | 'holiday' | 'work_from_home' | 'weekend';
export type WorkMode = 'office' | 'remote' | 'hybrid';
export type BreakType = 'lunch' | 'short' | 'prayer' | 'other';

export interface BreakRecord {
  id: number;
  break_start: string;
  break_end?: string;
  duration_minutes: number;
  duration_formatted: string;
  type: BreakType;
  note?: string;
  is_active: boolean;
}

export interface Attendance {
  id: number;
  user?: UserBrief;
  date: string;
  check_in?: string;
  check_out?: string;
  status: AttendanceStatus;
  work_mode: WorkMode;
  working_minutes: number;
  working_hours: number;
  break_minutes: number;
  overtime_minutes: number;
  is_late: boolean;
  late_minutes: number;
  note?: string;
  is_active: boolean;
  breaks: BreakRecord[];
}

// ─── Leave ────────────────────────────────────────────────────────────────────

export type LeaveStatus = 'pending' | 'manager_approved' | 'manager_rejected' | 'approved' | 'rejected' | 'cancelled';

export interface LeaveType {
  id: number;
  name: string;
  code: string;
  days_allowed_per_year: number;
  is_paid: boolean;
  requires_approval: boolean;
  carry_forward: boolean;
  allow_half_day: boolean;
  color: string;
  description?: string;
  is_active: boolean;
}

export interface Leave {
  id: number;
  user?: UserBrief;
  leave_type?: LeaveType;
  start_date: string;
  end_date: string;
  days_requested: number;
  is_half_day: boolean;
  half_day_period?: 'morning' | 'afternoon';
  reason: string;
  attachment_url?: string;
  attachment?: string | null;
  is_confidential?: boolean;
  status: LeaveStatus;
  status_label: string;
  can_be_cancelled: boolean;
  manager_remarks?: string;
  ceo_remarks?: string;
  reviewed_by_manager?: UserBrief;
  reviewed_by_ceo?: UserBrief;
  manager_reviewed_at?: string;
  ceo_reviewed_at?: string;
  created_at?: string;
}

export interface LeaveBalance {
  id: number;
  leave_type?: LeaveType;
  year: number;
  allocated: number;
  used: number;
  carried_forward: number;
  remaining: number;
}

// ─── Notifications ────────────────────────────────────────────────────────────

export type NotificationType = 'info' | 'success' | 'warning' | 'error';

export interface AppNotification {
  id: number;
  title: string;
  message: string;
  type: NotificationType;
  action_url?: string;
  is_read: boolean;
  read_at?: string;
  created_at: string;
}

// ─── Holiday ──────────────────────────────────────────────────────────────────

export interface Holiday {
  id: number;
  name: string;
  date: string;
  end_date?: string;
  description?: string;
  type: 'public' | 'optional' | 'restricted';
  is_recurring: boolean;
}

// ─── Audit Log ────────────────────────────────────────────────────────────────

export interface AuditLog {
  id: number;
  user?: UserBrief;
  action: string;
  module: string;
  description?: string;
  model_type?: string;
  model_id?: number;
  old_values?: Record<string, unknown>;
  new_values?: Record<string, unknown>;
  ip_address?: string;
  created_at: string;
}

// ─── API Response Shapes ──────────────────────────────────────────────────────

export interface PaginatedResponse<T> {
  data: T[];
  meta: {
    total: number;
    per_page: number;
    current_page: number;
    last_page: number;
  };
}

export interface ApiError {
  message: string;
  errors?: Record<string, string[]>;
}

// ─── Reports ──────────────────────────────────────────────────────────────────

export interface TeamMemberStatus {
  id: number;
  name: string;
  employee_id?: string;
  role: Role;
  department?: string;
  current_status: CurrentStatus;
  check_in?: string;
  check_out?: string;
  working_hours: number;
  is_late: boolean;
  late_minutes: number;
}

export interface DailySnapshot {
  date: string;
  total: number;
  working: number;
  on_break: number;
  checked_out: number;
  absent: number;
  on_leave: number;
  work_from_home: number;
  employees: TeamMemberStatus[];
}

export interface AttendanceSummary {
  user: { id: number; name: string; employee_id?: string; role: Role; department?: { id: number; name: string } | null; designation?: { id: number; name: string } | null };
  period: { start: string; end: string };
  total_days: number;
  present: number;
  absent: number;
  late: number;
  on_leave: number;
  work_from_home: number;
  total_working_hours: number;
  total_overtime_hours: number;
  avg_working_hours: number;
  working_days_in_period?: number;
  days_worked_excl_weekends?: number;
  assigned_tickets?: number;
  completed_tickets?: number;
  in_progress_tickets?: number;
  overdue_tickets?: number;
  ticket_worklog_hours?: number;
}
